### ISSUE TITLE
Infografía Fases y Ciclo de vida del desarrollo de software

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-1-infografia-Daniel-Velasco-Lopez#1]
[Infografía-Fases y ciclo de vida del desarrollo de software .pdf](https://github.com/user-attachments/files/16785263/Infografia-Fases.y.ciclo.de.vida.del.desarrollo.de.software.pdf)

**Comment by edgarmauricio123** [comment]
20 %

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
